### ISSUE TITLE
fetch is not a function

### ISSUE THREAD

**Issue by steveszc** [statecharts/xstate-viz#118]
When defining and invoking a service that uses fetch, an error is shown "fetch is not a function".
Clicking the event a second time allows you to continue clicking through the states.

This can be reproduced here: https://stately.ai/viz?gist=bbcb4379b36edea0458f597e5eec2f91

Console output:
```
instrument.js:109 TypeError: fetch is not a function
    at src (eval at <anonymous> (eval at se (realms-shim.umd.js:1323:12)), <anonymous>:19:42)
    at t.exec (interpreter.js:841:55)
    at t.execute (interpreter.js:200:14)
    at t.update (interpreter.js:226:12)
    at interpreter.js:106:15
    at t.process (scheduler.js:65:7)
    at t.schedule (scheduler.js:44:10)
    at t.send (interpreter.js:100:23)
    at simulationMachine.tsx:203:29
    at interpreter.js:1126:18
```

![xstate-fetch](https://user-images.githubusercontent.com/6877934/216206454-588d07ef-3ed7-4ad8-808d-76acf43a3617.gif)

**Comment by steveszc** [comment]
Oops! Just realized I posted this on the wrong repo and there is already an issue reporting this: https://github.com/statelyai/xstate-viz/issues/354
